# Generated by Django 5.2.6 on 2025-09-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagante',
            name='ciclo',
        ),
        migrations.AddField(
            model_name='pagante',
            name='ordem',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
